INSERT INTO COUNTRIES (COUNTRY_ID, NAME, PHONE_CODE) VALUES (1, 'ARGENTINA', 54);

INSERT INTO STATES (STATE_ID, NAME, COUNTRY_ID) VALUES (1, 'SANTA FE', 1);
INSERT INTO STATES (STATE_ID, NAME, COUNTRY_ID) VALUES (2, 'CORDOBA', 1);
INSERT INTO STATES (STATE_ID, NAME, COUNTRY_ID) VALUES (3, 'ENTRE RIOS', 1);


